modLoader = "javafml"
loaderVersion = "[1,)"
license = "All Rights Reserved"

[[mods]]
modId = "teamemc"
version = "0.1.0"
displayName = "Team EMC"
description = '''
Minimal Team EMC mod bootstrap.
'''

[[dependencies.teamemc]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.230,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.teamemc]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"
